import "./globals.css";
import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
const firaSans = Fira_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tailwind Css",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={firaSans.className}>{children}</body>
    </html>
  );
}
